### ISSUE TITLE
ImportError: ../ibstdc++.so.6/ version `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by moskomule** [sony/nnabla-ext-cuda#2]
Hi, nnabla seems very cool! 

While nnabla itself is successfully installed without any trouble via pip, I got errors as below when tried to `cmake`.  My environment is Ubuntu 16.04 and Python 2.7. 

Does any setting is not completed or is there a bug? Thank you for advance.

```
Traceback (most recent call last):
  File "/home/user/test/nnabla-ext-cuda/build-tools/cmake/get_nnabla_dir.py", line 16, in <module>
    import nnabla
  File "/home/user/.anaconda/envs/py27/lib/python2.7/site-packages/nnabla/__init__.py", line 16, in <module>
    import _init  # Must be imported first
ImportError: /home/user/.anaconda/envs/py27/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/user/.anaconda/envs/py27/lib/python2.7/site-packages/nnabla/libnnabla.so)
CMake Error at CMakeLists.txt:20 (string):
  string sub-command STRIP requires two arguments.


Traceback (most recent call last):
  File "/home/user/test/nnabla-ext-cuda/build-tools/cmake/get_nnabla_cpu_lib.py", line 17, in <module>
    import nnabla
  File "/home/user/.anaconda/envs/py27/lib/python2.7/site-packages/nnabla/__init__.py", line 16, in <module>
    import _init  # Must be imported first
ImportError: /home/user/.anaconda/envs/py27/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/user/.anaconda/envs/py27/lib/python2.7/site-packages/nnabla/libnnabla.so)
CMake Error at CMakeLists.txt:26 (string):
  string sub-command STRIP requires two arguments.


Downloading googletest
Downloading eigen
python: can't open file '/build-tools/cmake/get_setup_build_dir.py': [Errno 2] No such file or directory
CMake Error at CMakeLists.txt:55 (string):
  string sub-command STRIP requires two arguments.


Traceback (most recent call last):
  File "/home/user/test/nnabla-ext-cuda/build-tools/code_generator/generate.py", line 19, in <module>
    from generator_common.init_cpp_common import generate_init_cpp
ImportError: No module named generator_common.init_cpp_common
CMake Error at CMakeLists.txt:83 (include):
  include could not find load file:

    /build-tools/cmake/Utils.cmake


CMake Error at CMakeLists.txt:103 (nbla_warnings_disable):
  Unknown CMake command "nbla_warnings_disable".


-- Configuring incomplete, errors occurred!
```

**Comment by UhlSt** [comment]
Hi @moskomule, can you try to add `libgcc` to you conda installation
```
conda update libgcc
```
This should hopefully solve this problem.

**Comment by moskomule** [comment]
@UhlSt Yes, you are right. (And indeed the installation of `nnabla` itself was wrong.)
After installing `libgcc`, the building and installation succeeded. Thank you a lot.
